/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffNewRouteImport } from './routes/staff/new'
import { Route as PatientIdIndexRouteImport } from './routes/patient/$id/index'
import { Route as StaffIdEditRouteImport } from './routes/staff/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdIndexRoute = PatientIdIndexRouteImport.update({
  id: '/patient/$id/',
  path: '/patient/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIdEditRoute = StaffIdEditRouteImport.update({
  id: '/staff/$id/edit',
  path: '/staff/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staff/new': typeof StaffNewRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/$id/edit': typeof StaffIdEditRoute
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff/new': typeof StaffNewRoute
  '/patient': typeof PatientIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/$id/edit': typeof StaffIdEditRoute
  '/patient/$id': typeof PatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staff/new': typeof StaffNewRoute
  '/patient/': typeof PatientIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/$id/edit': typeof StaffIdEditRoute
  '/patient/$id/': typeof PatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staff/new'
    | '/patient/'
    | '/staff/'
    | '/staff/$id/edit'
    | '/patient/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/staff/new'
    | '/patient'
    | '/staff'
    | '/staff/$id/edit'
    | '/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/staff/new'
    | '/patient/'
    | '/staff/'
    | '/staff/$id/edit'
    | '/patient/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffNewRoute: typeof StaffNewRoute
  PatientIndexRoute: typeof PatientIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffIdEditRoute: typeof StaffIdEditRoute
  PatientIdIndexRoute: typeof PatientIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id/': {
      id: '/patient/$id/'
      path: '/patient/$id'
      fullPath: '/patient/$id/'
      preLoaderRoute: typeof PatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$id/edit': {
      id: '/staff/$id/edit'
      path: '/staff/$id/edit'
      fullPath: '/staff/$id/edit'
      preLoaderRoute: typeof StaffIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffNewRoute: StaffNewRoute,
  PatientIndexRoute: PatientIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffIdEditRoute: StaffIdEditRoute,
  PatientIdIndexRoute: PatientIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
